language: go

go:
  - "1.14.x"

services:
  - docker

branches:
  only:
    - main
    - /^release-[0-9]+\..*$/

addons:
  sonarcloud:
    organization: "open-cluster-management"
    token:
      secure: "YFiFNAu2WrtWQvNHyhYBQPRxWIVVO++Hi7muKT9WAVVNEmgNX2KbAQkwDosOX+hUKSRqIw/DgUs3NPN1O+X/O4L56iUFcrmoCXtJimZaWkiq3C9pseQs2LL7hM4ImyUlHhcBNqsmKMenUD3ayIujUvXOXfq1W4OQSRrDYPy2/zXshIJFmWgCeNsd+EWRVcAgWDnyv7K8iuD8PvC8ZigX5F+HDES1+gL8ldoj5nm5d4TMcAlfoWyXdc3koGJfVkSKtitXMzJfbd1+fZtmOH2/RL2cf1Kyhe17unzL3EEhg7dghMog5ZoDLOg3xmknUmTlcOnNouGltxvQ8Vcbm0T8v0hVC4HKecPzkVG4RsVyzNFwJsG5VZDVVjLEtN/Yb1op5EBFunkk/G+B85nZ3ralapDoyJ4mWuPpCfkiaD4vvR5BrwKT0D/T7rrQAMbGClzULo58HCkPb8xlU70xVWiHOsE4feqVrLB8xGnb6RhOjGfKxw7MY/RgXoLcKi4rSCpreZUYwO9vcpksN5C4PAaB1tyUHsVC+dgEwFCwLIBtBc5Np0qjq0sVKeqSoOWJDBrlU80w9g6rmEnbONQlnZjiIZb927l1P0rPg1u6einR3dGs3COv5/kmfRA/nPiYYumBqKSAVEAdSEN2Z7ixLTgLdkdTem+hF+p8mcp3ZulGaiU="

env:
  global:
    # Required
    - OS=linux
    - COMPONENT_TAG_EXTENSION="-${TRAVIS_COMMIT}"
    # Component Specific
    - COMPONENT_INIT_COMMAND=${TRAVIS_BUILD_DIR}/build/install-dependencies.sh
    - COMPONENT_BUILD_COMMAND=${TRAVIS_BUILD_DIR}/build/build.sh
    - COMPONENT_UNIT_TEST_COMMAND=${TRAVIS_BUILD_DIR}/build/run-unit-tests.sh
    - COMPONENT_E2E_TEST_COMMAND=${TRAVIS_BUILD_DIR}/build/run-e2e-tests.sh

stages:
  # - lint
  - build
  - unit-test
  - test-e2e
  # - publish

jobs:
  include:
    # - stage: lint
    #   name: "Run code lint"
    #   if: type = pull_request
    #   script: bash ${TRAVIS_BUILD_DIR}/build/run-code-lint.sh
    - stage: build
      name: "Build the image for pr and push it"
      if: type = pull_request
      script:
        - set -e
        - make copyright-check TRAVIS_BRANCH=${TRAVIS_BRANCH}
        - export COMPONENT_TAG_EXTENSION="-PR${TRAVIS_PULL_REQUEST}-${TRAVIS_COMMIT}"
        - |
          make
          make component/build
          make component/push
    - stage: build
      name: "Build the image with latest-dev tag and push it"
      if: type = push AND branch = main
      script:
        - set -e
        - export COMPONENT_VERSION="latest"
        - export COMPONENT_TAG_EXTENSION="-dev"
        - |
          make
          make component/build
          make component/push
    - stage: unit-test
      name: "Run unit test and collect coverage"
      script:
        - set -e
        - |
          make
          make component/test/unit
          set +e
          make stop-instrumented
          set -e
          make go/gosec-install
          gosec -fmt sonarqube -out gosec.json -no-fail ./...
          make sonar/js
    - stage: test-e2e
      name: "Deploy the image to a cluster and run e2e tests"
      if: type = pull_request
      script:
        - set -e
        - export COMPONENT_TAG_EXTENSION="-PR${TRAVIS_PULL_REQUEST}-${TRAVIS_COMMIT}"
        - |
          make
          make component/pull
          make component/test/e2e
    # - stage: publish
    #   name: "Publish the image to quay with an official version/sha tag and publish entry to integration pipeline stage"
    #   if: type = push AND branch =~ /^release-[0-9]+\..*$/
    #   script:
    #     - |
    #       make
    #       make pipeline-manifest/update PIPELINE_MANIFEST_COMPONENT_SHA256=${TRAVIS_COMMIT} PIPELINE_MANIFEST_COMPONENT_REPO=${TRAVIS_REPO_SLUG} PIPELINE_MANIFEST_BRANCH=${TRAVIS_BRANCH}
