kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: governance-policy-status-sync
rules:
- apiGroups:
  - "policy.open-cluster-management.io"
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch