apiVersion: apps/v1
kind: Deployment
metadata:
  name: governance-policy-status-sync
spec:
  replicas: 1
  selector:
    matchLabels:
      name: governance-policy-status-sync
  template:
    metadata:
      labels:
        name: governance-policy-status-sync
    spec:
      serviceAccountName: governance-policy-status-sync
      imagePullSecrets:
        - name: multiclusterhub-operator-pull-secret
      containers:
        - name: governance-policy-status-sync
          image: quay.io/open-cluster-management/governance-policy-status-sync:1.0.0-PR1-c8d4913b20b44dad68f6d6a6b848e755fa87db6e
          command:
          - governance-policy-status-sync
          args:
            - '--hub-cluster-configfile=/var/run/klusterlet/kubeconfig'
          imagePullPolicy: Always
          volumeMounts:
            - name: klusterlet-config
              mountPath: /var/run/klusterlet
          env:
            - name: WATCH_NAMESPACE
              value: calamari
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "governance-policy-status-sync"
      volumes:
        - name: klusterlet-config
          secret:
            secretName: endpoint-connmgr-hub-kubeconfig
            defaultMode: 420
